name: Deploy brute-force demo to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create ZIP package
        run: zip -r site.zip . -x ".git/*" -x ".github/*"

      - name: Publish to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: VAISDAY4TARGET            # <-- your exact Web App name
          package: site.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
